/**
 * Autogenerated by Thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
package org.wayne.evernote.edam.userstore;

/**
 * Contains constant values specified by this package.
 */
public class Constants {

  /**
   * The major version number for the current revision of the EDAM protocol.
   * Clients pass this to the service using UserStore.checkVersion at the
   * beginning of a session to confirm that they are not out of date.
   */
  public static final short EDAM_VERSION_MAJOR = (short)1;

  /**
   * The minor version number for the current revision of the EDAM protocol.
   * Clients pass this to the service using UserStore.checkVersion at the
   * beginning of a session to confirm that they are not out of date.
   */
  public static final short EDAM_VERSION_MINOR = (short)25;

}
